- hosts: localhost
  tasks:
  - name: ansible create directory example
    file:
      path: /var/lib/jenkins/dir1/
      state: directory
      owner: jenkins
      group: root
      mode: 0775
      recurse: yes    #This way, it will create the both directories, if they didn't exist.
