- hosts: slave1
  tasks:
  - name: ansible create directory example
    file:
      path: /var/lib/jenkins/file1.txt
      state: touch
      owner: jenkins
      group: jenkins
      mode: 0775
      #recurse: yes    #This way, it will create the both directories, if they didn't exist.
