- hosts: localhost
  tasks:
  - name: ansible create directory example
    file:
      path: /home/file1.txt
      state: touch
      owner: root
      group: root
      mode: 0775
      recurse: yes    #This way, it will create the both directories, if they didn't exist.
