---
- hosts: localhost
  #become: yes
  tasks:
  - name: log in as shrenikp7 and do something as root
    remote_user: root
    become: yes
    become_user: root
  - yum: name=ntp state=present
  - service: name=ntpd state=started enable=yes 
